DROP TABLE IF EXISTS TBL_JURNAL;

CREATE TABLE TBL_JURNAL (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  date VARCHAR(250) NOT NULL,
  title VARCHAR(250) NOT NULL,
  text VARCHAR(250) DEFAULT NULL,
  goalToday VARCHAR(250) DEFAULT NULL,
  progressMadeToday VARCHAR(250) DEFAULT NULL,
  moodToday VARCHAR(250) DEFAULT NULL,
  currentlyReading VARCHAR(250) DEFAULT NULL,
  Blob VARCHAR(250) DEFAULT NULL,
  websiteToday VARCHAR(250) DEFAULT NULL
);