CREATE TABLE jurnal(
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  data VARCHAR(250) NOT NULL,
  title VARCHAR(250) NOT NULL,
  goal VARCHAR(250) DEFAULT NULL,
  mood VARCHAR(250) DEFAULT NULL,
  reading VARCHAR(250) DEFAULT NULL
);