DROP TABLE IF EXISTS JURNAL;

CREATE TABLE JURNAL(
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  data VARCHAR(250) NOT NULL,
  title VARCHAR(250) NOT NULL,
  goalToday VARCHAR(250) DEFAULT NULL,
  moodToday VARCHAR(250) DEFAULT NULL,
  currentlyReading VARCHAR(250) DEFAULT NULL
);